### ISSUE TITLE
Disregard UTF-8 and X-UA tags (when applicable)

### ISSUE THREAD

**Issue by citrusui** [eduardinni/bootlint-online#12]
Bootlint Online, at the time of this writing, doesn't request HTTP headers when you enter a URL.

In the case of meta charset="UTF-8" and meta http-equiv="X-UA-Compatible" content="IE=edge">, these can be added server-side via .htaccess in Apache like so:

`AddDefaultCharset UTF-8`
`Header set X-UA-Compatible "IE=Edge"`

Would be nice to automatically detect this so I wouldn't keep getting 2 problems every time I check my site for errors.

**Comment by eduardinni** [comment]
Thanks for your feedback, now Bootlint Online checks for HTTP headers when W001 and W002 are found. :+1:
