### ISSUE TITLE
How could we integrate this linter on a react workflow?

### ISSUE THREAD

**Issue by grillermo** [eduardinni/bootlint-online#22]
Hey Eduardo, i work for aliada were we are doing react and i was wondering how we could use this to lint our html and match it to our components. I see that you do react too and maybe have thought about this.

**Comment by eduardinni** [comment]
Hi Guillermo, I think you can achieve that linter flow using Jest + Enzyme + Bootlint (Node.js API).

https://github.com/facebook/jest
https://github.com/airbnb/enzyme
https://github.com/twbs/bootlint

Let me know if I could help with something else. ✌️
