### ISSUE TITLE
HTTPS Error after submit a validation attempt

### ISSUE THREAD

**Issue by lordlouis** [eduardinni/bootlint-online#28]
The console shows this while submitting a validation attempt:
`Mixed Content: The page at 'https://www.bootlint.com/' was loaded over HTTPS, but requested an insecure resource 'http://bootlint-online.api.bootlint.com/check'. This request has been blocked; the content must be served over HTTPS.`

![2018-07-13-130312_1366x744_scrot](https://user-images.githubusercontent.com/16420218/42706644-21399192-869d-11e8-98f5-e9862a0f26a4.png)
Using Google Chrome 65.0.3325.181 (Build oficial) (64 bits)

**Comment by conficient** [comment]
The same result with Edge (v42) and Firefox (v61)

**Comment by eduardinni** [comment]
Thanks for the report, it is fixed now :)
