### ISSUE TITLE
Doesn't support Rails ERB?

### ISSUE THREAD

**Issue by MyklClason** [eduardinni/bootlint-online#29]
Basically I'm auto-generating Bootstrap 3 which I'm then converting to Bootstrap 4 using http://upgrade-bootstrap.bootply.com/, but it's complicated by having embedded server side.

Here is the failing subset of the code:

```
<ul class="nav navbar-nav">
  <li><%= link_to "Events", events_path  %></li>
</ul>
```

I imagine it's trying to parse <%= %> as HTML tags, which they aren't. PHP also uses <? ?> for embedding server side code. Any chance to simply ignore "Tags" that start and end with a special character? If that is indeed the error.

**Comment by eduardinni** [comment]
Hello, this implementation only supports HTML. You can try this tool with the rendered output of the ERB.
