### ISSUE TITLE
Paste code to check

### ISSUE THREAD

**Issue by vanillajonathan** [eduardinni/bootlint-online#8]
It would be nice with an option to paste code to check for sites that are locally hosted or behind firewalls.

So you can just copy & paste the webpage code and lint it.

**Comment by eduardinni** [comment]
Thanks for your feedback.

I hope to get this feature asap. :+1:

**Comment by maxbrauer** [comment]
Would be nice to get in a <select> option HTTP and  HTTPS, for lazy persons.
